### ISSUE TITLE
SignalR 3.0 Milestone Doc Checklist

### ISSUE THREAD

**Issue by bradygaster** [dotnet/AspNetCore.Docs#10887]
Doc issues we will need to satisfy prior to our 3.0 launch. The work items immediately below a ready for the preview 3 docathon.

* [x] Add client feature matrix for SignalR clients
 * Issue #14378 (P1 3.0)
* [x] Add All Java Options to Config Page(@mikaelm12)
  * Issue: #11125 (P2 3.0)
* [x] Java Streaming Support (@mikaelm12)
  * Issue: #9771 (P2 3.0)
  * Implementation PR: https://github.com/aspnet/SignalR/pull/3301
* [x] Java Upload Streaming Support 
  * Issue: #14308
  * Implementation PR: https://github.com/aspnet/AspNetCore/pull/8222
* [x]  Client to server streaming .NET and TS clients (@BrennanConroy)
  * Issue: #10630 (P0 3.0)
* [ ]  C++ Client (@BrennanConroy)
  * Issue: #10888 (P0 3.0)
* [x] TypeScript Client's keepAliveInterval (@mikaelm12)
  * Issue: #10783 (P2 3.0)
* [x] Don't indicate HubConnectionBuilder.build() starts the connection (@mikaelm12)
  * Issue: #11106 (P2 3.0)
* [x] Add Java Doc for SignalR Java Client TransportEnum (@mikaelm12)
  * Issue: #11134 (P2 3.0)
* [ ] Endpoint routing (@halter73)
  * Issue: #11127 (P2 3.0)
  * Implementation PR: https://github.com/aspnet/AspNetCore/pull/7608
* [x] IAsyncEnumerable Hub Method Return (@halter73)
  * Issue: #11129 (P1 3.0)
  * Implementation PR: aspnet/AspNetCore#6791
  * Doc PR: #11140
* [x] Automatic Reconnection (@halter73)
  * Issue: #11093 (P0 3.0)
* [ ] Connection lifecycle (@halter73)
  * Issue #9280 (P1 3.0)
* [x] Validate Auth Policy Doc (@bradygaster)
  * Issue #13050

The following are reminder issues for 3.0 RTM wrap-up to help ensure we don't forget to document client API changes. These have nothing actionable yet for the preview 3 docathon.

* [x] TypeScript client updates (@tdykstra)
  * Issue: #10485 (P2 3.0)
  * Update to `@microsoft/signalr`
* [x] JavaScript client updates (@tdykstra)
  * Issue: #10484 (P2 3.0)
  * Update to `@microsoft/signalr`

**Comment by bradygaster** [comment]
@muratg @BrennanConroy @halter73 @mikaelm12 @davidfowl FYI

**Comment by davidfowl** [comment]
We'll need to introduce the new endpoint routing wire up.

**Comment by bradygaster** [comment]
Closing, and I'm moving the still-unfinished #11127 to the new tracking item, #23357
