### ISSUE TITLE
3.1 Update Routing to controller actions MASTER ISSUE

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#13871]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

- [x]  HttpMethodAttribute doesn't implement IActionConstraint #15463
- [ ]  How to set a global fallback route? #14733
- [x]  Additional information about endpoint-routing #14655 (and related issue :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/17125)
- [x]  Unexpected behavior of Url.Action() #12221

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak can you assign someone to outline the changes need for the 3.0 version of  `Routing to controller actions` ?

**Comment by rynowak** [comment]
I'm probably the right person for that.
