### ISSUE TITLE
Container list: Create a web API and MongoDB

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16196]
18,666 PV
---
This is the Container issue for this doc.  Reopen each issue you are working on so the owner is notified.

- [x] Replace NewtonSoftJson reference for Version 3.1 and newer #20791
- [x] Using asynchronous MongoClient APIs #21991
- [x] Suggestion: Add clarification for <port> in 'Test the web API' section #21920
- [x] Book Class #20773
- [x] MonoDB Rest API Tutorial : explain port #20488
- [x] The Startup.cs snipet is missing the following code. The current version produces an error where 'Configuration' doesn't get resolved #16514
- [x] MongoDB C# driver support #15942
- [x] ReplaceOne() method not working properly on .Net Core 3.0 #14829
- [x] MongoDB tutorial: Update to 3.0 and use proper snippets #14651
- [ ] what is the point to use Pascal casing in json to match CLR object's property names? #14623
- [x] Something about this article need adjusts #17256
- [x] Something about this article need adjusts #17271
- [x] Error in example code #17692
- [x] HTTP 500 thrown on a POST with the code from this document #17518
- [x] Does MongoDb .Net Drive use System.Text.Json? #18409
- [x]  ArgumentNullException: Value cannot be null. (Parameter 'name') #21105
- [x] Add additional JSON property so Swagger looks like non Swagger URL #21836
- [x] Missing information #23435

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by BenHayat** [comment]
Any answer to my question?

> Does MongoDb .Net Drive use System.Text.Json?

**Comment by guardrex** [comment]
I'm going to move this to backlog just so that we can close this old milestone ... it keeps popping up on me and getting in the way when working with new issues. 🏃

**Comment by Rick-Anderson** [comment]
@markjbrown take a look at these issues when you send me the updated code.

**Comment by markjbrown** [comment]
Thanks @Rick-Anderson. I'm going to loop in a member on our team on this. Will revert back in about a week.

Thanks again!
