### ISSUE TITLE
Master issue for: Authorize with a specific scheme

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16190]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

- [ ]  Multiple authentication schemes #16389

Closed and completed.
- [x] Multiple Cookie authentication #16156
- [x] no authentication scheme is specified when default is not specified #15695 
- [x] It is not clear how challenging works with multiple authentication schemes. #12437
- [x] Is policy always required when specifying authentication schemes? #12438
- [x] Multiple Authorities don't seem to be working #12177

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by udlose** [comment]
Any movement on any of these?  Specifically, #12177, #12438, #15695.

**Comment by Rick-Anderson** [comment]
@blowdart  please review or assign a reviewer.

**Comment by kmk713** [comment]
Any update on #16389 ? It's really clogging up the app insights with error logs

**Comment by blowdart** [comment]
@kmk713 16389 seems more of a bug than a docs issue. Open an issue on the asp.net repo for it and I can triage it there.

**Comment by udlose** [comment]
Any updates on any of these issues?

**Comment by oliviervaillancourt** [comment]
I'm also interested in this topic.  We are using two different Idp that issue JWT (Auth0 + AAD).  Obviously for any given request, only one of those Idp is in play.  So being able to see token validate error for just that one is critical.   The best I could find up to now to "reduce" the problem is to Opt-in to the `OnMessageReceived` event of the JwtBearerHandler and does an `issuer` check.

if the issuer (in the JWT) is matching the Scheme, then continue normal processing. if it's not then return a `AuthenticationResult.NoResult` (alt: return `AuthenticationResult.Failure("Issuer not matching...skipping true validation")` .  This seems to avoid the IDX10501 in the logs.

Not ideal though...  Hope that helps and looking for forward to resolution.

**Comment by udlose** [comment]
@Rick-Anderson why was this closed?  Has it been fixed?

**Comment by Rick-Anderson** [comment]
This was tracking issues, It looks like they've all been closed.

**Comment by udlose** [comment]
According to https://github.com/dotnet/AspNetCore.Docs/issues/16389#issuecomment-620126765 this Issue was supposed to include it.  I see it linked above under a "mention" but nothing else.  I was originally asked to follow both tickets for update.

**Comment by kakins** [comment]
> I'm also interested in this topic. We are using two different Idp that issue JWT (Auth0 + AAD). Obviously for any given request, only one of those Idp is in play. So being able to see token validate error for just that one is critical. The best I could find up to now to "reduce" the problem is to Opt-in to the `OnMessageReceived` event of the JwtBearerHandler and do an `issuer` check.
> 
> if the issuer (in the JWT) is matching the Scheme, then continue normal processing. if it's not then return a `AuthenticationResult.NoResult` (alt: return `AuthenticationResult.Failure("Issuer not matching...skipping true validation")` . This seems to avoid the IDX10501 in the logs.
> 
> Not ideal though... Hope that helps and looking for forward to resolution.
> 
> Not ideal but I did write a blog post on a way to "reduce this issue" https://oliviervaillancourt.com/posts/Fixing-IDX10501-MultipleAuthScheme. Feedback welcomed.
> 
> (@blowdart) If you think this technique weakens security, I would really like to hear about that. Thanks

This approach seemed to work for me as well.  At least in my case, it was better to implement `OnMessageReceived` for each of my schemes rather than creating a new `JwtBearerHandler` as discussed in the aforementioned blog post.  This is because I'm using AAD in addition to a custom IdentityServer scheme.  I couldn't find a way to customize IdentityServer's bearer handler so as to avoid the log messages described here.

**Comment by mradulmodi** [comment]
Facing same issue when using multiple Jwt token validation schemes in .NET Core Middleware. Using 6 authentication schemes and 5 of them throw exception creating noise in AI Logs. Code stub adding authentication schemes. Also which one are we supposed to follow for updates this or #16389 

```
foreach (var tokenAuthority in Authorities)
            {
                builder.AddJwtBearer(tokenAuthority.Key, options =>
                 {
                     options.Audience = ClientId;
                     options.Authority = tokenAuthority.Value;
                     options.TokenValidationParameters = new TokenValidationParameters
                     {
                         ValidIssuers = <Issuers>,
                         ValidateIssuer = true,
                         ValidAudiences = <audiences>,
                         ValidateLifetime = true,
                         ValidateIssuerSigningKey = true,
                     };
                     options.EventsType = typeof(AuthenticationJwtBearerEvents);
                 });
            }
```
