### ISSUE TITLE
Container issue: Handle errors in ASP.NET Core web APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16385]
This is the Container issue for this doc.  Reopen each issue you are working on so the owner is notified.
![image](https://user-images.githubusercontent.com/3605364/81107975-b8445e80-8eb3-11ea-9e97-af6ff10d85f7.png)

Feedback hub comments:
* Move the global web api exception handler to the base controller and not add dozens of global handlers to the ASP.NET main program.
*  code doesn't even compile!

PU issues:
- [ ] Need information focused on the production of errors (especially accumulation of message #15333
- [x] Use ApiBehaviorOptions.ClientErrorMapping sample code problem #15055
- [ ] Insufficient Information on how error handling should be implemented. #16372
- [ ] No documentation on *how* to implement problem details factory #17837

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please find some time to squeeze this in. Not urgent, but would like to get this addressed.
