### ISSUE TITLE
master issue: WS-Federation

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16508]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

- [ ]  Update Authenticate users with WS-Federation #9706 - @Rick-Anderson  can take this issue. Change all of ASP.NET Core 2.0 to just ASP.NET Core

closed 

- [x] WsFederation Support for multiple Identity Providers? #16507
- [x] Whether ADFS token encryption has been supported or not？ #11999 @Tratcher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@blowdart can you review these issues? cc @j3fflan3

**Comment by blowdart** [comment]
You closed them? I answered individually so the users get notified.

**Comment by mariocatch** [comment]
Is the WS-Federation documentation updated to asp.net core 3.1? I don't think it is based on what's on the live docs, but wanted to follow up with this.

**Comment by Rick-Anderson** [comment]
@mariocatch  what's not up to date?

```
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
        endpoints.MapRazorPages();
    });
```

Is 3.1

**Comment by mariocatch** [comment]
Hi, thanks for following up.

I was referring mostly to this introduction:

> This tutorial demonstrates how to enable users to sign in with a WS-Federation authentication provider like Active Directory Federation Services (ADFS) or Azure Active Directory (AAD). It uses the ASP.NET Core 2.0 sample app described in Facebook, Google, and external provider authentication.

> For ASP.NET Core 2.0 apps, WS-Federation support is provided by Microsoft.AspNetCore.Authentication.WsFederation. This component is ported from Microsoft.Owin.Security.WsFederation and shares many of that component's mechanics. However, the components differ in a couple of important ways.

If I'm mistaken, then my apologies.

I have a large website using ws-federation on .net 4.6.1 right now and I'm looking into upgrade paths to asp core 3.1. I can't find any actual end-to-end usage or implementation of it in any Microsoft sample. And most other usage is using owin still.

If you happen to know of something I might be missing that would be greatly appreciated! Thanks.
