### ISSUE TITLE
Dependency injection master issue

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17298]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

Not PU issues:
- [ ] Define "factory method" #17901
- [ ] Include a topic about how the service collection works #14973
- [ ] Disposing of service instances not created by the container #16773
- [ ] Call services from main ObjectDisposedException explanation #17860
- [ ]  Update document regarding the accumulation of Transient services #17766
- [ ]  DI Break up samples #17299

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1&branch=pr-en-us-17152)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
