### ISSUE TITLE
Master issue: Key storage providers in ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17625]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

PU issues:
- [ ] Azure Storage code sample: token will expire and cause havoc #14004 - related to  #13738
- [ ]  Is there a way to persist keys to Azure Key Vault? #12592
- [ ]  How to use AddDataProtection in an async way #17038
- [ ] EF Core DB First Documentation #17615

**_Not_** PU issues:
- [ ] 

![image](https://user-images.githubusercontent.com/3605364/78582981-e1e56980-77d1-11ea-8759-8e944b20b33c.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59850a13-1322-0c54-9fd3-75ce837c2b1a
* Version Independent ID: 7d481dae-d27d-909c-a35d-bad66c7508d2
* Content: [Key storage providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio#entity-framework-core)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
