### ISSUE TITLE
Container issue: Host ASP.NET Core on Linux with Nginx

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17735]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

PU issues:
- [ ]  Should explain how testCert.crt/testCert.key can be generated #17724
- [ ]  https://github.com/dotnet/AspNetCore.Docs/issues/14005
- [ ]  Deploy to subdirectory #15464
- [ ] Missing SignalR config? #11403

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
