### ISSUE TITLE
Master issue: Session and state management in ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17881]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

PU issues:
- [ ]  https://github.com/dotnet/AspNetCore.Docs/issues/16542
- [ ]  HttpContext.Session.IsAvailable will cause an exception if not created by DI, there should be a safe way to test if session is available #17103
- [ ]  Loading session state asynchronously - potential usage problem #17873
- [ ] 

**_Not_** PU issues:
- [ ] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2#load-session-state-asynchronously-1)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
