### ISSUE TITLE
Options pattern Container issue: Check here first

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18291]
25K PV

This is the Container issue for this doc.  Reopen each issue you are working on so the owner is notified.

Not PU:
- [x] IOptionsMonitor<MyOptionsWithDelegateConfig> in the example will not update with changes #17146
- [x] Add DI options sample #18292
- [x] Add basic sample of options pattern #17150
- [x] Add an example of using a custom IValidateOptions<TOptions> #17413
- [x] Options validation with FluentValidation #17452
- [x] Discussion on the Options pattern, which includes remarks by D🦆: https://github.com/dotnet/docs/issues/22886. Content on the the PR at https://github.com/dotnet/docs/pull/22907/files might be something to drop into the coverage over here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
