### ISSUE TITLE
Bundle and minify master issue

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18523]
This is the master issue for this doc.  Reopen each issue you are working on so the owner is notified.

9.7K PV

PU issue
- [ ] Bundler & Minitifier is no longer actively worked on or supported #11610
- [ ] Replace Gulp with tooling that offers similar functionality #12367
- [ ] HTTP/2 not mentioned #11619

Not PU:
- [ ] Mention that you need a bundling package/tool #18502
- [ ]  External links #18899
- [ ] This doesn't work in Asp.Net 3.1.5 in Mac #19150

See this [SO post](https://stackoverflow.com/a/50546448/502537) by former team member and https://github.com/dotnet/aspnetcore/issues/5415

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-5.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT  See this [SO post](https://stackoverflow.com/a/50546448/502537) by former team member and https://github.com/dotnet/aspnetcore/issues/5415
and this issue

**Comment by mkArtakMSFT** [comment]
Closing this as this is not a priority for us. Nor we have a good story to recommend here.
