### ISSUE TITLE
Blazor Hybrid tracking

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#24956]
## Articles (ToC and physical/URL locations)

Topic | Location/filename | Issue | PR | &nbsp;
--- | --- | --- | --- | ---
Static files<sup>1</sup> | `aspnetcore/blazor/hybrid/static-files.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25674 | https://github.com/dotnet/AspNetCore.Docs/pull/25891 | [Live Topic](https://docs.microsoft.com/aspnet/core/blazor/hybrid/static-files)
Routing & Navigation<sup>2</sup> | `aspnetcore/blazor/hybrid/routing-and-navigation.md` | &mdash; | https://github.com/dotnet/AspNetCore.Docs/pull/25130 | [Live Topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing)
Reuse Razor components<sup>3</sup> | `aspnetcore/blazor/hybrid/reuse-razor-components.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25675 | https://github.com/dotnet/AspNetCore.Docs/pull/25847 | [Live Topic](https://docs.microsoft.com/aspnet/core/blazor/hybrid/reuse-razor-components)
~Integrate with native UI<sup>4</sup>~ **DROPPED&dagger;** | ~`aspnetcore/blazor/hybrid/integrate-with-native-ui.md`~ | https://github.com/dotnet/AspNetCore.Docs/issues/25676 | :x: | :x:
~Access native platform features<sup>5</sup>~ **DROPPED&dagger;** | ~`aspnetcore/blazor/hybrid/access-to-platform-features.md`~ | https://github.com/dotnet/AspNetCore.Docs/issues/25677 | :x: | :x:
~Native look and feel<sup>6</sup>~ **DROPPED&dagger;** | `aspnetcore/blazor/hybrid/native-look-and-feel.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25678 | :x: | :x:
Globalization & Localization<sup>7</sup> | `aspnetcore/blazor/hybrid/globalization-localization.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25679 | &mdash; | &mdash;
Use browser dev tools<sup>8</sup> | `aspnetcore/blazor/hybrid/developer-tools.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25382 | https://github.com/dotnet/AspNetCore.Docs/pull/25384<br>https://github.com/dotnet/AspNetCore.Docs/pull/25484 | [Live Topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/developer-tools)
Security & Identity Overview<sup>9</sup> | `blazor/hybrid/security/index.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25453, https://github.com/dotnet/AspNetCore.Docs/issues/25461, https://github.com/dotnet/AspNetCore.Docs/issues/25771 | https://github.com/dotnet/AspNetCore.Docs/pull/25555, https://github.com/dotnet/AspNetCore.Docs/pull/25791 | [Live Topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/)
Security considerations (added per Security Overview updates) | `blazor/hybrid/security/security-considerations.md` | &mdash; | https://github.com/dotnet/AspNetCore.Docs/pull/25791 | [Live Topic](https://docs.microsoft.com/aspnet/core/blazor/hybrid/security/security-considerations)
~Security & Identity Threat mitigation<sup>10</sup>~ **DROPPED&dagger;** | `blazor/hybrid/security/threat-mitigation.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25680 | :x: | :x:
~Security & Identity With AAD<sup>11</sup>~ **DROPPED&dagger;** | ~`blazor/hybrid/security/azure-active-directory.md`~ | https://github.com/dotnet/AspNetCore.Docs/issues/25681 | :x: | :x:
~Security & Identity With AAD B2C<sup>12</sup>~ **DROPPED&dagger;** | ~`blazor/hybrid/security/azure-active-directory-b2c.md`~ | https://github.com/dotnet/AspNetCore.Docs/issues/25682 | :x: | :x:
Publish Overview<sup>13</sup> `publish` folder | `blazor/hybrid/publish/index.md` | https://github.com/dotnet/AspNetCore.Docs/issues/25683 | &mdash; | &mdash;

&dagger;See the issue for details.

**Notes**:

5 &mdash; Will be covered by https://github.com/dotnet/AspNetCore.Docs/issues/25675 in the *Reuse web components* topic.
7 &mdash; Document https://github.com/dotnet/maui/issues/2532.
9 &mdash; Create a folder at `aspnetcore/blazor/hybrid/security`.
13 &mdash; Create a folder at `blazor/hybrid/publish`.Cross-link landing and general guidance. Cross-link out to the Blazor host and deploy overview, and cross-link to this Hybrid apps publish overview from there.

## Additional Tasks

* [x] In the *Error handling* topic for macOS with .NET MAUI dev tools, react to resolution of https://github.com/dotnet/maui/issues/5561. Context at https://github.com/dotnet/AspNetCore.Docs/pull/25384#discussion_r834701257. **UPDATE**: This now has a dedicated issue at https://github.com/dotnet/AspNetCore.Docs/issues/26039.
* [x] To fix https://github.com/dotnet/AspNetCore.Docs/issues/25453, un-comment the remarks in the topic. **PR:** https://github.com/dotnet/AspNetCore.Docs/pull/25670

## Process

Working in order down this list ...

- [x] **Thursday (2/10)**: General tutorials work for existing tutorials. This isn't directly related to Hybrid apps coverage outside of preparing for cross-links, but I'd like to get this resolved first. https://github.com/dotnet/AspNetCore.Docs/pull/24960
- [x] **Thursday-Thursday (2/10-2/17)**: PRs loaded for review as they're ready with GH and email pings for review.
  - [x] PR 1 https://github.com/dotnet/AspNetCore.Docs/pull/24965
    * Preview notice INCLUDE
    * Blazor Overview (`blazor/index.md`) update
    * Tooling topic *Additional Resources* cross-link to the Hybrid tutorials overview
    * Supported platforms update
    * Hosting models update
    * Hybrid Overview (`blazor/hybrid/index.md`)
    * Hybrid Tutorials folder and overview (placed on PR 1 to unblock the remaining PRs)
  - [x] PR 2: .NET MAUI tutorial https://github.com/dotnet/AspNetCore.Docs/pull/24977
  - [x] PR 3: WinForms tutorial https://github.com/dotnet/AspNetCore.Docs/pull/24989
  - [x] PR 4: WPF tutorial https://github.com/dotnet/AspNetCore.Docs/pull/25043
- [x] **Friday (2/18)**: `no-loc` update to add "Blazor Hybrid" https://github.com/dotnet/AspNetCore.Docs/pull/25064

## Notes

* All topics to receive a preview notice at the top.
* A 'Blazor Hybrid' column as already been added to the [Blazor.Docs project](https://github.com/dotnet/AspNetCore.Docs/projects/35) for tracking work.
* Although final release is apparently 7.0, we'll version topics for 6.0 or later so that they'll show up during preview.
* Some overview topics, at least initially, may only contain minimal guidance. The main value of some of them is to provide a cross-link landing from other places around the doc set and for external links. I recommend their use and have included them where needed here.
* I defer on "contextual ToCs" but mention that whatever is done I recommend not breaking a reader's location in the ToC as they read and work down our ToC.
* After further reflection, especially along the lines of the prior bullet, I think Hybrid apps security and host/deploy content **_should be in the Hybrid node_**. Again, I seek to avoid readers losing their place and getting frustrated trying to figure out where they just were.
* Conforms to the plan for Blazor tutorial location (ToC and physical location) for the reasons discussed at https://github.com/dotnet/AspNetCore.Docs/issues/24900.
* Samples
  * https://github.com/danroth27/BlazorWinForms
  * https://github.com/danroth27/BlazorHybridWpf (we're reacting to https://github.com/dotnet/maui/issues/3526 with an RCL workaround)
  * In the .NET MAUI repo: https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples

## Additional remarks from the discussion

> There's no formal name for using Blazor with WPF and WinForms. The ".NET MAUI Blazor app" name comes from the corresponding template name, but we don't have templates for using Blazor with WPF and WinForms. ".NET MAUI Blazor app" merely refers to a .NET MAUI app with at least one `BlazorWebView` control. We will avoid defining a name for Blazor-WPF and Blazor-WinForms for now and instead refer to the task, something such as, "Add a `BlazorWebView` to a {WPF|Windows Forms} app."

> Hybrid apps use a blend of native and web technologies. A Blazor Hybrid app uses Blazor in a native client app. Razor components always run natively in the .NET process and render web UI to an embedded web view control using a local interop channel. WebAssembly isn't used at all in Hybrid apps.

> There's no plan to add `BlazorWebView` articles to the WPF and Windows Forms doc sets. .NET MAUI is a bit different in that the `BlazorWebView` is built into the framework. .NET MAUI docs will link to the Blazor docs wherever appropriate.

## Additional remarks for the content and tutorials

* .NET MAUI tutorial
  * Include instructions both for getting started using the .NET MAUI Blazor template and manually adding a `BlazorWebView` to an existing .NET MAUI app, similar to what we'll need to document for WPF & WinForms.
  * Getting started guidance on both Windows and non-Windows machines.
* WPF and WinForms tutorials: Go off of the sample apps.
* Blazor Hybrid overview: Check out the presentations (email) as a starting point.

### Initial coverage

- [x] Overview - In `blazor/index.md`, add a Blazor Hybrid section. https://github.com/dotnet/AspNetCore.Docs/pull/24965
- [x] Tutorials (ToC entry) - Create a folder named `tutorials`. Move the current `tutorials.md` file content to an overview, and add a redirect. Move this node down two spots under "Tooling". https://github.com/dotnet/AspNetCore.Docs/pull/24960
  - [x] Overview - Dervied from existing `tutorials.md` with additional remarks, as needed. Include a cross-link to the Hybrid app tutorials overview. (`aspnetcore/blazor/tutorials/index.md`)
  - [x] Get-started (ToC cross-link to the Learn Module for Blazor Server)
  - [x] Build a Blazor todo list app (Server or WASM) (`aspnetcore/blazor/tutorials/build-a-blazor-app.md`)
  - [x] SignalR with Blazor (Server or WASM) (`aspnetcore/blazor/tutorials/signalr-blazor.md`)
- [x] Supported platforms - In `blazor/supported-platforms.md`, mention Blazor Hybrid. "We test on and support the latest platform webview control versions (WebView2 on Windows, Chrome on Android, Safari on iOS and macOS)." https://github.com/dotnet/AspNetCore.Docs/pull/24965
- [x] Tooling - In `blazor/tooling.md`, cross-link to the Blazor Hybrid tutorials overview. https://github.com/dotnet/AspNetCore.Docs/pull/24965
- [x] Hosting models - In `blazor/hosting-models.md`, add a Blazor Hybrid section that covers the arch and pros/cons. https://github.com/dotnet/AspNetCore.Docs/pull/24965
- [x] Hybrid apps (ToC entry) - Create a folder named `hybrid`.
  - [x] Overview - Add `blazor/hybrid/index.md` with initial (minimal) overview remarks (anything more detailed than what the Hosting Models article covers). This article mostly serves as a cross-link landing. https://github.com/dotnet/AspNetCore.Docs/pull/24965
  - [x] Tutorials (ToC entry) - Create a folder at `blazor/hybrid/tutorials`.
    - [x] Overview - Cross-link landing page. (`blazor/hybrid/tutorials/index.md`)
    - [x] Blazor Hybrid with .NET MAUI (`aspnetcore/blazor/hybrid/tutorials/maui.md`) https://github.com/dotnet/AspNetCore.Docs/pull/24977
    - [x] Blazor Hybrid with WPF (`aspnetcore/blazor/hybrid/tutorials/wpf.md`) - Supply components via an RCL workaround (https://github.com/dotnet/maui/issues/3526). https://github.com/dotnet/AspNetCore.Docs/pull/25043
    - [x] Blazor Hybrid with Windows Forms (`aspnetcore/blazor/hybrid/tutorials/windows-forms.md`) https://github.com/dotnet/AspNetCore.Docs/pull/24989

**Comment by danroth27** [comment]
>  Where is BlazorWebView is going to be covered? Is it supposed to be part of the upcoming topic "Integrate with native UI" (aspnetcore/blazor/hybrid/integrate-with-native-ui.md)? ... to then be THE platform-agnostic place for coverage (covers for WPF and WinForms, too)? ... and the .NET MAUI topic will be deleted and redirected to the "Integrate with native UI" topic over here?

The high level concept of using a BlazorWebView to build a Blazor Hybrid app should be covered in the Blazor Hybrid Overview and in the Blazor hosting models topic. The individual BlazorWebView controls for .NET MAUI, WPF, and Windows Forms will get covered in the onboarding tutorials and through API docs. The .NET MAUI BlazorWebView ships as part of .NET MAUI and is [documented](https://docs.microsoft.com/dotnet/maui/user-interface/controls/blazorwebview) along with the other MAUI controls. This topic has a bunch of overlapping content with the Blazor Hybrid docs that we can replaced with links to the Blazor Hybrid Overview and .NET MAUI Blazor onboarding tutorial. The "Integrate with native UI" topic was intended specifically for discussing how you can use a BlazorWebView alongside other native UI.

I'm not sure what doc content is needed for https://github.com/dotnet/docs-maui/issues/281. I've reached out to @TanayParikh 
to get more clarity on that.
