### ISSUE TITLE
.NET 7: Update What's new in ASP.NET Core 7.0

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26326]
- [x]  [Preview 1](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/)
   - [x] #26345 
   - [x]  #26821 
   - [x] #26683
   - [x]  #26346
   - [x] #26445
   - [x] #26569 Is that new to .NET 6 or .NET 7?
   - [x] #26566
   - [x] Improved console output for dotnet watch
   - [x] Configure dotnet watch to always restart for rude edits
- [x]  [Preview 2](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/)
  - [x] [Infer API controller action parameters that come from services](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/#infer-api-controller-action-parameters-that-come-from-services) fixed in #26230
  - [x]  #26291
  - [x] Binding arrays and StringValues from headers and query strings in minimal APIs [Program.cs](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/bindingArrays/7.0-samples/todo/Program.cs) #26410
  - [x]  #26341
- [x]  [Preview 3](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/)
  - [x] [Support for route handler filters in minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/#support-for-route-handler-filters-in-minimal-apis)  done in: [Filters in Minimal API apps](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0#filters-in-minimal-api-apps)
  - [x]  #26352
  - [x] `code #26378`: #26423
  - [x] #26355
  - [x] #26845
  - [x] #26846
  - [x]  #26356
 
- [x]  [Preview 4](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/)
  - [x] Typed results for minimal APIs
  - [x] HTTP/2 performance improvements
  - [x] #26480
  - [x] [OpenAPI improvements for minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#openapi-improvements-for-minimal-apis) 
    - [x] [the Microsoft.AspNetCore.OpenApi package](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#openapi-improvements-for-minimal-apis)
    - [x] https://github.com/dotnet/AspNetCore.Docs.Samples/issues/79
    - [x]  #27127
    - [x] [Self-describing minimal APIs with IEndpointMetadataProvider and IEndpointParameterMetadataProvider](https://github.com/dotnet/AspNetCore.Docs/issues/26793) @tdykstra 
   - [x] #26818 @tdykstra 
   - [x] #26819 @tdykstra 
  - [x] #26514
  - [x] #26515 
- [x]  [Preview 5](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-5/)
  - [x] #26155
  - [x] #26540
- [x]  [Preview 6](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/)
  - [x] #26541
  - [x] #26542 @tdykstra 
  - [x] #26545
  - [x] #26546
  - [x] #26547
- [x]  [Preview 7](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/)
  - [x] #26682
  - [x]  #26683
  - [x]  #26685
  - [x] #26686
  - [x] #26687
- [x]  [RC1](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/)
  - [x]  #27002
  - [x] #27003
  - [x] #27005 https://github.com/dotnet/AspNetCore.Docs.Samples/issues/45
  - [x] #27121
  - [x] #26949 
  
- [RC2 ](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-2/)
  - [x] #26542 @tdykstra 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Version Independent ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Content: [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-7.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33261](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33261)

**Comment by Rick-Anderson** [comment]
@martincostello if you look at [`is:open label:"code help wanted"`](https://github.com/dotnet/AspNetCore.Docs/labels/code%20help%20wanted) there are a bunch of samples we're looking for help writing. Grab any that look interesting.

**Comment by martincostello** [comment]
Happy to do #26345 if the other person doesn't want to as I implemented it in the first place 😃

**Comment by JamesNK** [comment]
Need to include gRPC JSON transcoding. There was a small section on the preview 4 blog post. This blog post goes into more detail: https://devblogs.microsoft.com/dotnet/announcing-grpc-json-transcoding-for-dotnet/

**Comment by Jhstvf4t** [comment]
I don't have money anymore to go out to the workshop, I want to eat, let alone me

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky @fiyazbinhasan  new samples to write at  [`is:open label:"code help wanted"`](https://github.com/dotnet/AspNetCore.Docs/labels/code%20help%20wanted)

**Comment by sammychinedu2ky** [comment]
ok would look into it and see  @Rick-Anderson

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson are there any plans to add a section about route groups?
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#route-groups

Maybe in the overview doc
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson are there any plans to add a section about route groups? https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#route-groups

Yes, can you update a sample to add route groups?
