### ISSUE TITLE
Blazor .NET 7 tracking issue

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#26364]
## Derived from the 7.0 roadmap

🟢 = Ready&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ✔️ = Done&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 🛑 = Wait on PU to finish&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ❌ = No action required

Status | Live | Issue | PR | Item | PU Links/<br>Blog
:---: | :---: | :---: | :---: | --- | :---:
✔️ | [Live 1](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#navigation-options)<br>[Live 2](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#handleprevent-location-changes) | &mdash; | #26919<br>#26947 | Expose location changing event for NavigationManger | [42638](https://github.com/dotnet/aspnetcore/pull/42638) [42877](https://github.com/dotnet/aspnetcore/issues/42877) [43079](https://github.com/dotnet/aspnetcore/pull/43079) [Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/#handle-location-changing-events)
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#invoke-component-methods-externally-to-update-state) | &mdash; | #26574 | Calling InvokeAsync(StateHasChanged) causes page to fallback to default culture | [28521](https://github.com/dotnet/aspnetcore/issues/28521)
✔️ | [Live 1](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-7.0&pivots=windows)<br>[Live 2](https://docs.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-7.0) | &mdash; | #26575 #26576 | Empty Blazor project template | [32832](https://github.com/dotnet/aspnetcore/issues/32832) [Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#empty-blazor-project-templates)
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#blazor-custom-elements) | &mdash; | #26587 | Productize the custom elements support package | [38447](https://github.com/dotnet/aspnetcore/issues/38447) [Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#blazor-custom-elements-no-longer-experimental)
✔️ | [Live 1 (top)](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0)<br>[Live 2](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0#bind-across-more-than-two-components) | &mdash; | https://github.com/dotnet/blazor-samples/pull/33<br>#26771<br>#27288 | Design proposal: Bind get/set/after modifiers | [39837](https://github.com/dotnet/aspnetcore/issues/39837)<br>https://github.com/dotnet/razor-compiler/pull/70
❌ | &mdash; | &mdash; | &mdash; | Components don't reset their received parameters during hot reload updates<br><br>**Tooling update** | [31272](https://github.com/dotnet/aspnetcore/issues/31272)
✔️ | [Live 1](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-7.0#customize-authentication) [Live 2](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0#custom-authentication-request-scenarios) | &mdash; | #26968<br>See **MSAL Support** below | Better MSAL support for additional scenarios | [38122](https://github.com/dotnet/aspnetcore/issues/38122)
❌ | &mdash; | &mdash; | &mdash; | Developers targeting browser-wasm can use Web Crypto APIs<br><br>**We don't document this subject, so it only will appear in the What's New coverage per #27288.** | [40074](https://github.com/dotnet/runtime/issues/40074) [Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#system-security-cryptography-support-on-webassembly)
❌ | &mdash; | &mdash; | &mdash; | Generic Blazor component can't correctly infer it's type when type has an additional constraint<br><br>**🪲 fix** | [25588](https://github.com/dotnet/aspnetcore/issues/25588)
❌ | &mdash; | &mdash; | &mdash; | CascadingTypeParameter problem<br><br>**🪲 fix** | [38479](https://github.com/dotnet/aspnetcore/issues/38479)

**MSAL support**

- [x] [Dynamic and extensible authentication requests](https://github.com/dotnet/aspnetcore/issues/42580)
- [x] [Blazor Azure ADB2C Authentication popup size does not match content](https://github.com/dotnet/aspnetcore/issues/37365)
- [x] [Support passing more options to WASM AAD auth](https://github.com/dotnet/aspnetcore/issues/32782)
- [x] [Add support for "prompt="select_user" with WASM / MSAL](https://github.com/dotnet/aspnetcore/issues/32640)
- [x] [Blazor Webassembly AAD and AAD B2C support improvements](https://github.com/dotnet/aspnetcore/issues/27549)
- [x] [.Net 5 RC2 - Blazor Wasm - AAD B2C SignUpSignIn catch error 'AADB2C90118' to start Password Reset userflow](https://github.com/dotnet/aspnetcore/issues/27119)
- [x] [Provide a way to set loginHint in Blazor with AAD auth](https://github.com/dotnet/aspnetcore/issues/19925)
- [x] [In Blazor WebAssembly, allow dynamic query string parameters when redirecting to IDP](https://github.com/dotnet/aspnetcore/issues/33784)

## Moved to .NET 8

* [Enable integration with 3rd party assets management solutions](https://github.com/dotnet/aspnetcore/issues/38445)
* Improve prerendering and authentication experience in Blazor
* [Ability to run multiple Blazor server / Web assembly apps in the same document](https://github.com/dotnet/aspnetcore/issues/38128)
* [Perform a pass cleaning up the web templates](https://github.com/dotnet/aspnetcore/issues/30162)
* [Consider shipping ObjectGraphDataAnnotationsValidator / ValidateComplexTypeAttribute](https://github.com/dotnet/aspnetcore/issues/28640)
* [Design for solving transient disposables on Blazor Server](https://github.com/dotnet/aspnetcore/issues/26676)
* [Pause and resume server-side Blazor circuits](https://github.com/dotnet/aspnetcore/issues/30344)
* [How to configure HttpClient base address in Blazor Server using IHttpClientFactory](https://github.com/dotnet/aspnetcore/issues/25758)
* [More control over circuits lifetime (ability to monitor circuit activity and terminate from client/server](https://github.com/dotnet/aspnetcore/issues/30287)
* [Server-side Blazor: Provide APIs/Extension Points for Circuit Eviction](https://github.com/dotnet/aspnetcore/issues/17866)
* [Add DateOnly and TimeOnly support to model binding &amp; routing](https://github.com/dotnet/aspnetcore/issues/34591)
* [Image element to display images that are not accessible through HTTP endpoints](https://github.com/dotnet/aspnetcore/issues/25274)
* [Real multithreading (on supported browsers](https://github.com/dotnet/aspnetcore/issues/17730)
* [Continued improvements to Mono Method Body Replacement](https://github.com/dotnet/runtime/issues/57365)

## Derived from 7.0 issues/PRs not on the roadmap or other sources

Status | Live | Issue | PR | Item | PU Links/<br>Blog
:---: | :---: | :---: | :---: | --- | :---:
✔️ | &mdash; | &mdash; | #27316 | Changes in default authentication scheme handling | [Announcement](https://github.com/aspnet/Announcements/issues/490)
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-7.0&pivots=windows#net-webassembly-build-tools-1) | #27292 | #27302 | WASM build tools addition | 
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0#custom-validation-attributes-3) | #26457 | #26590 | Custom validation attribute with DI | [39445](https://github.com/dotnet/aspnetcore/pull/39445) [Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/#inject-services-into-custom-validation-attributes-in-blazor)
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-7.0&pivots=linux) | #26459 | #26621 | WASM debug default browser going to Edge | [33088](https://github.com/dotnet/aspnetcore/issues/33088)
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0#built-in-input-components) | #26460 | #26753 | InputX component use outside of an EditContext/Form | [35640](https://github.com/dotnet/aspnetcore/pull/35640)
✔️ | &mdash; | #26519 | #26537 | Prerendering `<head>` content, merge `_Layout` & `_Host`, other template changes | [40512](https://github.com/dotnet/aspnetcore/pull/40512) [41991](https://github.com/dotnet/aspnetcore/pull/41991) [35158](https://github.com/dotnet/aspnetcore/pull/35158)
✔️ | [Live 1](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0#quickgrid-component)<br>[Live 2](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/built-in-components?view=aspnetcore-7.0) | &mdash; | #26628 | Experimental data grid package https://aspnet.github.io/quickgridsamples/ | [aspnet/AspLabs 517](https://github.com/aspnet/AspLabs/pull/517) [Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#experimental-quickgrid-component-for-blazor)
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#navigation-options) | &mdash; | #26947 | NavigationManager supports state | [42534](https://github.com/dotnet/aspnetcore/pull/42534)
✔️ | [Live 1](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0#root-level-virtualization)<br>[Live 2](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0#control-the-spacer-element-tag-name) | &mdash; | #26649 | Virtualization enhancements, esp. controlling spacer element | [42446](https://github.com/dotnet/aspnetcore/pull/42446)
❌ | [Live](https://docs.microsoft.com/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0#built-in-event-arguments) | &mdash; | &mdash; | `MouseEventArgs` updates<br><br>**Covered via the existing ref source link in the article and via the What's New coverage per #27288.** | [42451](https://github.com/dotnet/aspnetcore/pull/42451)
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#loading-progress-indicators) | &mdash; | #26744 | Blazor WASM new loading UI | [42548](https://github.com/dotnet/aspnetcore/pull/42548) [Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/#new-blazor-loading-page)
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-7.0#blazor-webassembly-authentication-logging) | #27173 | #27175 #27176 #27273 #27277 | Make it simpler for customers to investigate Blazor Auth issues | [39412](https://github.com/dotnet/aspnetcore/issues/39412) [Blog Post](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-2/#improved-diagnostics-for-authentication-in-blazor-webassembly)
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0) | #27016 | #27083<br>#27311<br>#27385<br>https://github.com/dotnet/blazor-samples/pull/53 | New JS interop + obsolete `InvokeUnmarshalled` ... update WASM snippet sample app, the *Perf* topic, and the example in the *Call JS from .NET* topic. | [42814](https://github.com/dotnet/aspnetcore/pull/42814) [dotnet/runtime #70133](https://github.com/dotnet/runtime/issues/70133) [dotnet/runtime #66304](https://github.com/dotnet/runtime/pull/66304)<br>[RC1 Blog Post](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/#net-javascript-interop-on-webassembly)<br>[Blog Post (WebAssembly multithreading experimental)](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-2/#webassembly-multithreading-experimental)
✔️ | &mdash; | &mdash; | #27029 | Consider registering the authentication state provider conditionally | [41235](https://github.com/dotnet/aspnetcore/issues/41235) [41247](https://github.com/dotnet/aspnetcore/pull/41247)
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-7.0&pivots=windows#net-webassembly-build-tools-1) | &mdash; | #27171 |  WebAssembly build tools for .NET 6 projects | [Blog post](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/#net-webassembly-build-tools-for-net-6-projects)

## Other

Status | Live | Issue | PR | Item | PU Links/<br>Blog
:---: | :---: | :---: | :---: | --- | :---:
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0#root-level-virtualization) | &mdash; | #26649 | Root-level virtualization incomp w/overflow-y:scroll workaround for <7.0 content | [37659](https://github.com/dotnet/aspnetcore/issues/37659)
✔️ | &mdash; | &mdash; | #26827 | Change Kestrel's HTTPS endpoint defaults to improve developer experience | [42016](https://github.com/dotnet/aspnetcore/issues/42016)<br>[aspnet/Annoucements #486](https://github.com/aspnet/Announcements/issues/486)
✔️ | [Live](https://docs.microsoft.com/aspnet/core/release-notes/aspnetcore-7.0#blazor) | &mdash; | #27288 | What's New content | #26326
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70#blazor) | &mdash; | #27288 | Migration content | #26800

## 7.0 Blazor Hybrid

Status | Live | Issue | PR | Item | PU Links
:---: | :---: | :---: | :---: | --- | :---:
❌ | &mdash; | &mdash; | &mdash; | Blazor with maui can not use &lt;InputSelect&gt; or &lt;select&gt;<br><br>**🪲 fix** | [4325](https://github.com/dotnet/maui/issues/4325)
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-7.0#globalization-and-localization) | #25679 | #27702 | Blazor Desktop tenets: Global readiness | [2532](https://github.com/dotnet/maui/issues/2532)
❌ | &mdash; | &mdash; | &mdash; | Blazor Desktop test infrastructure and plans<br><br>**Engineering only** | [2543](https://github.com/dotnet/maui/issues/2543)
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-7.0) | &mdash; | #26918 | Support configurability in opening external URLs | [4338](https://github.com/dotnet/maui/issues/4338)
❌ | &mdash; | &mdash; | &mdash; | Hot Reload on MAUI Blazor App does not works.<br><br>**🪲 fix** | [2527](https://github.com/dotnet/maui/issues/2527)
✔️ | [Live](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/?view=aspnetcore-7.0&pivots=maui) | &mdash; | #25771 | Blazor Desktop: Support for auth | [2529](https://github.com/dotnet/maui/issues/2529)
❌ | &mdash; | &mdash; | &mdash; | Blazor Desktop tenets: Security<br><br>**Moved to internal PU tracking.** | [2540](https://github.com/dotnet/maui/issues/2540)
❌ | &mdash; | &mdash; | &mdash; | Blazor Desktop tenets: Performance<br><br>**Engineering only** | [2531](https://github.com/dotnet/maui/issues/2531)
❌ | &mdash; | &mdash; | &mdash; | Blazor Desktop tenets: Accessibility<br><br>**External article review performed by PU.** | [2541](https://github.com/dotnet/maui/issues/2541)
❌ | &mdash; | &mdash; | &mdash; | Blazor Desktop dev tools enablement<br><br>**Engineering only** | [2542](https://github.com/dotnet/maui/issues/2542)
✔️ | &mdash; | &mdash; | &mdash; | Docs: Blazor hybrid walkthrough / getting started<br><br>**Covered per our tutorials here.** | [3684](https://github.com/dotnet/maui/issues/3684)
❌ | &mdash; | &mdash; | &mdash; | Blazor hybrid project template updates<br><br>**AFAICT, no specific action is required beyond what I updated as part of the tutorial updates post-release 👇.** | [4127](https://github.com/dotnet/maui/issues/4127)
✔️ | [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-7.0#unhandled-exceptions-in-windows-forms-and-wpf-apps) | &mdash; | #27702 | Exception handling for blazor webview | [4441 (dotnet/maui #4441)](https://github.com/dotnet/maui/issues/4441)<br>[5535 (dotnet/maui #5535)](https://github.com/dotnet/maui/issues/5535)<br>[40765](https://github.com/dotnet/aspnetcore/pull/40765)

## 7.0 Post GA

Status | Issue | PR | Item
:---: | :---: | :---: | ---
✔️ | &mdash; | #27535 | Rotate 7.0 content to tops and update `ms.date`
✔️ | &mdash; | https://github.com/dotnet/blazor-samples/pull/57 | Update package refs at `dotnet/blazor-samples`
✔️ | &mdash; | #27618,  #27634 (MAUI)<br><br>#27639 (WinForms & WPF) | Blazor Hybrid tutorial updates, including screenshot updates.<br><br>[LIVE Blazor-MAUI doc](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-7.0)<br>[LIVE Blazor-WinForms doc](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-7.0)<br>[LIVE Blazor-WPF doc](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-7.0) 
✔️ | &mdash; | #27678 | macOS/VS4Mac pivot in the MAUI-Blazor tutorial<br><br>[LIVE Blazor-MAUI doc](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-7.0)
❌ | &mdash; | &mdash; | Open an issue to replace in-text (usually non-working) examples with samples repo-based fully working cut-'n-paste examples. List the sections that require updates. This issue will be targeted for EOY or 23Q1.<br><br>**I decided to move this to an entry on the project tracking issue at #24615 to be addressed in '23. I think Blazor security node work along with regular work items are going to take up the 🦃 Day to 🎅 Day/🎆 Day period. If so, this won't be reached until 23Q1. Some topics probably won't get this treatment until they're scheduled for their first overhaul after arriving in the doc set.**
✔️ | &mdash; | #27579 | Cross-link API docs
✔️ | #27386 | #27534 | Updates for the *Client-side development* `[JSImport]`/`[JSExport]` interop article (`client-side/dotnet-interop.md`).
✔️ | #27133 | #27553 | Drop VS4Mac prerelease warning for Blazor Hybrid.
❌ | &mdash; | &mdash; | Final updates to *What's New* and *Migration* content<br><br>**No updates required. The commented-out content for the new JSImport/JSExport for JS apps was activated in an earlier PR.**
✔️ | &mdash; | #27518 | Remove point-in-time remark on `DateOnly`/`TimeOnly` and PU cross-link.

## Blog posts for cross-links

* ~https://devblogs.microsoft.com/dotnet/announcing-asp-net-core-in-dotnet-7/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-2/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-5/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/~ :+1: **_Done!_**
* ~https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/~ :+1: **_Done!_**

## 7.0 preview/RC PU issues for analysis

This section of linked issues is assessed for items that didn't make the roadmap but have a bearing on docs. This section will be removed after the last batch for RC2 are assessed. RC1 and RC2 will be assessed after their milestone versions release.

* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-preview1~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-preview2~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-preview3~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-preview4~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-preview5~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-preview6~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-preview7~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-rc1~ :+1: **_Done!_**
* ~https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+milestone%3A7.0-rc2~ :+1: **_Done!_**

## PU roadmap

[ASP.NET Core Roadmap for .NET 7 (dotnet/aspnetcore #39504)](https://github.com/dotnet/aspnetcore/issues/39504)

**Comment by guardrex** [comment]
# 🎉🍾🕺💃🥳🎈 

# ***That's IT!*** Blazor 7.0 docs rollout complete! 

Closing the tracking issue now. Follow-up items are tracked by https://github.com/dotnet/AspNetCore.Docs/issues/24615.
