### ISSUE TITLE
Blazor project tracking 2023

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#28001]
# 2023

## History

* For the 2022, see [Blazor project tracking 2022 (dotnet/AspNetCore.Docs #24615)](https://github.com/dotnet/AspNetCore.Docs/issues/24615).
* For the 2021, see [Blazor project tracking 2021 (dotnet/AspNetCore.Docs #19286)](https://github.com/dotnet/AspNetCore.Docs/issues/19286).

## Doc ideas

Not **ALL** of these will be worked. This is an idea list/check list that don't rise to the level of opening an issue at this time.

* [ ] Consider adding a code example for the `MutationObserver` pattern where its discussed.
* [ ] File uploads topic: Fix accessibility of the yes/no icons. Use: `<span aria-hidden="true">XXXXX</span><span class="visually-hidden">XXXXX</span>`
* [ ] Add guidance on ***the reason(s)*** for using partial classes and base classes (inheritance) with pros and cons of each (partial = only splitting, base class = splitting and multiple-inheritance, useful in library-provided API scenarios).
* [ ] Per Steve's .NET Conf talk, shouldn't we briefly cover [`FileSystem` API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem) use in Blazor apps?
* [ ] Let's run through the [`testassets` pieces in the framework](https://github.com/dotnet/aspnetcore/tree/main/src/Components/test/testassets) to see what might be helpful for devs to see in docs. It's a large task tho because there's so much there. This probably can't be worked in 23H1, possibly for 23Q3 tho.
* [ ] There's great PU-provided memory leak guidance on https://github.com/dotnet/aspnetcore/issues/43221. Take a look and see if/what could go into docs, possibly even just by linking the PU issue to cover it in the near-term.
* [ ] More for '23 than '22, I'm moving over a wrap-up item from the 7.0 tracking issue to this issue for work later: "Open an issue to replace in-text (usually non-working) examples with samples repo-based fully working cut-'n-paste examples. List the sections that require updates. This issue will be targeted for EOY or 23Q1."
* [ ] It would probably be nice to create a `QuickGrid` example that opens and closes a detail record component without losing the page and scroll position of the grid. For context, see https://github.com/dotnet/blazor-samples/issues/58.
* [ ] I think I need to cross-link https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-7.0#denial-of-service-dos-attacks to the DoS NOTE on message size limit, particularly in the fundamentals signalr config guidance.
* [ ] Firefox debug support per https://github.com/dotnet/AspNetCore.Docs/issues/27411. Check back in 23Q1 on status because there's currently no PU issue to track on.
* [ ] The state management doc is a bit scatter 🧠 with the new coverage on in-memory state preservation given the introduction is about lost state scenarios. Also, we don't do anything specific for cascading. However, this is a low priority for '22 and can be worked in 23H1 after consulting with the PU. https://github.com/dotnet/AspNetCore.Docs/issues/27296
* [ ] After .NET 7 releases, it's best to have PU 🐈 look over the SignalR-Blazor enhancements for SignalR config (in the SignalR doc and the WASM/Server Host and Deploy docs) and SignalR client logging (in the Logging doc).
* [ ] It would be nice to adopt file-scoped namespaces for 6.0 or later examples and snippet samples. This is ***very low priority*** tho! 😄 What might happen is just all ***new*** examples get the treatment.
* [ ] There's about a half-dozen or so cases of using compiler directives around the docs to control code for debug vs. release configs. Confirm that configuration/environment can't manage these cases or that using configuration/environment wouldn't make sense for them.
* [ ] Ask Tanay to review the new example at [*Fundamentals* > *DI* > *Utility base component classes to manage a DI scope* section](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/dependency-injection#utility-base-component-classes-to-manage-a-di-scope).
* [ ] Chat with Javier about the **_WHY_** aspects on https://github.com/dotnet/AspNetCore.Docs/pull/26620#issuecomment-1205513721. I'd like to know why the RID works with the MSBuild prop (`/p:RuntimeIdentifier={RID}` but the self-contained setting doesn't (`/p:SelfContained=false`).
* [ ] Chat with Tanay about https://docs.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?view=aspnetcore-6.0 per https://github.com/dotnet/AspNetCore.Docs/pull/26557. Is this the best way to showcase event callbacks with dymanic components?
* [ ] When https://github.com/dotnet/docs/issues/27395 is resolved and Mono/WASM MSBuild props are covered, update the cross-links from the targets file to the new official doc. Links can be located on the PR that added them at https://github.com/dotnet/AspNetCore.Docs/pull/24493.

## UE pass tracking

Only includes topics that weren't reached in '21 or new topics added in '21.

- [ ] Components - The *Overview* topic is getting a bit too long again. Time to look and see if we can split out content into new, smaller sub-topics in this node. #27811, #27931
  - [ ] Control \<head> content
  - [ ] Dynamically-rendered components
- [ ] Call a web API from WebAssembly &mdash; Although this topic had it's UE pass in '21 on #22410, the web API aspects rely on the main doc set web API article, and churn in the web API doc can break the Blazor experience in this topic.
- [ ] Security and Identity &mdash; See :point_right: #20708, #19807, and #19226. I placed an ellipsis in the `App` component example INCLUDE(s) to cover 6.0 churn. See: https://github.com/dotnet/AspNetCore.Docs/issues/23696. Work https://github.com/dotnet/AspNetCore.Docs/issues/25026 in this node. There are general remarks and some specific items for AAD/AAD B2C and `UserManager`/`SignInManager` at #27279.
  - [ ] Overview &mdash; Either here or in the Blazor Server *Overview*: #22405 Make a note that for the `[Authorize]` attribute applied with `@attribute` (or in code) to a component that it automatically handles tossing an unauthenticated user to the IdP for sign in. It requires considerably less markup/code to implement than an `<AuthorizeView>` for the mere purpose of including a custom `RedirectToLogin` component in the project for the `<NotAuthorized>` render fragment.
  - [ ] Blazor Server &mdash; https://github.com/dotnet/AspNetCore.Docs/issues/27432
    - [ ] Overview &mdash; Review, work was done on :point_right: https://github.com/dotnet/AspNetCore.Docs/pull/20119 and mention https://github.com/dotnet/AspNetCore.Docs/issues/19797#issuecomment-779294104.
    - [ ] Threat mitigation
    - [ ] Additional scenarios &mdash; Review, work was done on :point_right: https://github.com/dotnet/AspNetCore.Docs/pull/20119. Also, see :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/22122. Refresh token info request: https://github.com/dotnet/AspNetCore.Docs/issues/26086.
  - [ ] Blazor WebAssembly
    - [ ] Standalone with Authentication library &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21510, https://github.com/dotnet/aspnetcore/issues/30068, https://github.com/dotnet/AspNetCore.Docs/issues/23712
    - [ ] Standalone with Microsoft Accounts: See #21816
    - [ ] Standalone with AAD
    - [ ] Standalone with AAD B2C &mdash; "custom user flows" language https://github.com/dotnet/AspNetCore.Docs/issues/21144. Take a look at signup-signin Azure UI per https://github.com/dotnet/aspnetcore/issues/39401#issuecomment-1009511236. Note to readers that [B2C with Graph API isn't supported](https://github.com/dotnet/AspNetCore.Docs/issues/26127).
    - [ ] Hosted with AAD &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21983, https://github.com/dotnet/AspNetCore.Docs/issues/26165
    - [ ] Hosted with AAD B2C &mdash; "custom user flows" language https://github.com/dotnet/AspNetCore.Docs/issues/21144; see :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21640. Take a look at signup-signin Azure UI per https://github.com/dotnet/aspnetcore/issues/39401#issuecomment-1009511236. Take a look at an edge case for wanting the id token in spite of the default code flow: https://github.com/dotnet/aspnetcore/issues/39311#issuecomment-1138777859 w/addl discussion at https://github.com/dotnet/aspnetcore/pull/41873 ... I don't think that we'll cover it, but take a look, especially if MS IdP/MSAL/Azure docs cover it and it can be cross-linked (and this assumes that we're even keeping this topic in the first place. It might get the 🔪.) Note to readers that [B2C with Graph API isn't supported directly ... the host ASP.NET Core app can expose Graph API via web API calls](https://github.com/dotnet/AspNetCore.Docs/issues/26127).
    - [ ] Hosted with Identity Server &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21842 and also see https://github.com/dotnet/AspNetCore.Docs/issues/22753 (Was it just VS not creating the project with the correct Identity config to run OOB when deployed to Azure directly from VS?) Consider splitting out custom domains from IdS, and check on the B1 requirement IdS-only scnearios (it might not be a requirement in that case). See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/24067#issuecomment-980033383. If the doc doesn't already say that DP must be configured for automatic key management, make it say that and cross-link to the main doc set doc section (see: https://github.com/dotnet/AspNetCore.Docs/issues/27989#issuecomment-1369179894).
    - [ ] Additional scenarios - Look for split-out opportunities. Possibly add an introductory ToC with section descriptions. Consider if the *Unauthenticated or unauthorized web API requests in an app with a secure default client* section could be better cross-linked/mentioned explicitly in the individual WASM security topics (https://github.com/dotnet/AspNetCore.Docs/issues/22217 and https://github.com/dotnet/AspNetCore.Docs/pull/22220). Consider making an INCLUDE out of the prerendering guidance and shooting a copy of that into the *Prerendering and Integration* topic (https://github.com/dotnet/AspNetCore.Docs/issues/23441). Check on the "outgoing `HttpResponseMessage`" language in the [API doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.authorizationmessagehandler), per discussion at #26739 (and **_respond back on that issue with the final answer from the PU_**).
  - [ ] Content Security Policy
- [ ] Debug WebAssembly &mdash; Resolve :point_right: #23373 ... and we'll probably need to show full files everywhere we refer to `tasks.json`/`launch.json` due to https://github.com/OmniSharp/omnisharp-vscode/issues/4542. See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/23777
- [ ] WebAssembly native dependencies
- [ ] Test components - Specifically, let's consider hosting example component tests for WASM and Server (`TestServer`). https://github.com/dotnet/AspNetCore.Docs/issues/25263
- [ ] Progressive Web Applications &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21100
- [ ] Host and deploy: Apache for hosted WASM/sub-app scenarios might need more work. See 👉 https://github.com/dotnet/AspNetCore.Docs/pull/24519#issuecomment-1008480134.
  - [ ] Overview &mdash; Perhaps for *Routing*, too, but clarify the navigation behavior of `NavigationManager.NavigateTo`. See :point-right: https://github.com/dotnet/AspNetCore.Docs/pull/22146#issuecomment-827802596.
  - [ ] Blazor Server &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21226
  - [ ] Blazor WebAssembly &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/19979 and https://github.com/dotnet/AspNetCore.Docs/issues/21829#issuecomment-803192673 and validate `web.config` post PR https://github.com/dotnet/AspNetCore.Docs/pull/24950 and in light of discussion on https://stackoverflow.com/a/69888016 and https://stackoverflow.com/a/70967738. Probably add a tagged SO filter link: `https://stackoverflow.com/questions/tagged/blazor+iis+compression`
  - [ ] WebAssembly deployment layout
- [ ] Blazor Server and EF Core
- [ ] External to the Blazor node: Scaffolding topic sections that pertain to Blazor &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/8434#issuecomment-808893911

**_SEPARATE WORK ITEM FOR SECURITY NODE_**

- [ ] Consider a topic on Azure Functions with Blazor WASM+AAD/B2C: My understanding is that it was NOT possible ... at least for B2C (perhaps AAD always worked). See https://github.com/dotnet/aspnetcore/issues/35794#issuecomment-908683517. That discussion occurred back in August, 2021, so things may have improved by now for B2C/WASM/AF. *IMO, this architecture makes a lot of sense for WASM serverless scenarios.* :+1:

## UE pass tracking

New topics added recently that haven't had the 🦖 **Rex Treatment**&trade; 🦖 ... or at least haven't had a pass for a few years ...

* Blazor Server and EF Core
* Multiple hosted WASM apps article
* Debug WASM article
* Call web API topic: I'd like to divorce this from the main doc set's web API article in favor of a small Minimal APIs-based web API app for the experiences in the topic. I think churn on the main doc set article may have broken the cut-'n-paste, fully working examples that I have. I either need to update the examples to match the latest guidance in the web API article or place a dedicated app example in this topic, and I favor the latter because of on-going web API article churn ... this is a fragile 💥 setup because I don't maintain both articles.
* File Uploads article
* File Downloads article
* Test article
* PWA article
* Performance best practices article
* State Management article
* Virtualization article: https://github.com/dotnet/AspNetCore.Docs/issues/27537
* Blazor Hybrid
  * Overview
  * Tutorials
    * Overview
    * .NET MAUI
    * Windows Forms
    * WPF
  * Routing and navigation
  * Static files
  * Dev Tools
  * Reuse components
