### ISSUE TITLE
8.0: Feature tracking gRPC

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#28609]
This issue is tracking all 8.0 related features that must be accounted for in the gRPC docs from preview to post RTW to make sure we don't miss anything. 

 This issue description will be continuously updated.  This issue will move between monthly sprints as we go.

After each doc is updated, update the What's new in ASP.NET Core 8.0 doc with links.  This has to be done fast since many folks are in that file, checked out no longer than 2 hours.

----------------------------
Links to Announcements/What's New:

- [What's new in .NET 8  Preview](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8)

Devblogs.microsoft.com and other announcements:
- [ASP.NET Core updates in .NET Preview 1](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#http-3-enabled-by-default)
- [ASP.NET Core updates in .NET Preview 2](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-2/)
- [ASP.NET Core updates in .NET Preview 3](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-3/)
- [ASP.NET Core updates in .NET 8 Preview 4](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-4/)
- [ASP.NET Core updates in .NET 8 Preview 5](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/)

----------------------------
**Tracking features to issues and PR's**

- [x] HTTP/3 support enabled by default in 8 (available 6-7 but was not default enabled)  (Preview 1)
   - Tracking issues:
      - #28607 8.0 Update: Troubleshooting gRPC

- [x] [Support for named pipes in Kestrel create an IPC server and client](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#support-for-named-pipes-in-kestrel) (Preview 1)
   - Completed by @JamesNK  and recently updated in PR ##28282 for doc [Inter-process communication with gRPC](https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-8.0)
   
- [x] [HTTP/2 over TLS (HTTPS) support on macOS](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#http-2-over-tls-https-support-on-macos) (Preview 1)
   - [x] @JamesNK updated [Troubleshoot gRPC on .NET Core: Unable to start ASP.NET Core gRPC app on macOS](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-8.0#unable-to-start-aspnet-core-grpc-app-on-macos) with PR #28246 
   - [x] [Tutorial: Create a gRPC client and server in ASP.NET Core:  Run the service](https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-8.0&tabs=visual-studio#run-the-service) needs an update to the TLS/MacOs note.   To be addressed while updating for 8.0 in issue #28251

- [x] [gRPC JSON transcoding no longer requires http.proto and annotations.proto](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#grpc-json-transcoding-no-longer-requires-http-proto-and-annotations-proto) (Preview 1)  Copying http.proto and annotations.proto files into your app is no longer required. In .NET 8 preview 1 those files are included in the NuGet package and automatically referenced for you.  
  - Tracking issue: #29080

See somewhat related 8.0 feature tracking for SignalR #28610 

- [x] gRPC supports native AOT in .NET 8. Native AOT enables publishing gRPC client and server apps as small, fast native executables.   JamesNK has already provided the doc for this here: [gRPC and native AOT](https://learn.microsoft.com/aspnet/core/grpc/native-aot?view=aspnetcore-8.0) in the related docs.

Old May [Associated WorkItem - 96056](https://dev.azure.com/msft-skilling/Content/_workitems/edit/96056)

---

**Comment by wadepickett** [comment]
Tracked and updated for April, will re-open for March.

**Comment by wadepickett** [comment]
Reopening for May tracking.

**Comment by wadepickett** [comment]
Verified: No new features or changes specifically for gRPC for preview 4 during May.   Closing this issue for tracking the review for features for gRPC in May.  Will recreate for June to review for next release.

[ASP.NET Core updates in .NET 8 Preview 4 - .NET Blog (microsoft.com)](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-4/)

**Comment by wadepickett** [comment]
Opening for June sprint.

**Comment by wadepickett** [comment]
Nothing new for gRPC announced in preview 5.

**Comment by wadepickett** [comment]
Verified complete for June
