### ISSUE TITLE
8.0: Feature tracking SignalR: July Previews

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#28610]
This issue is tracking all 8.0 related features that must be accounted for in the SignalR docs from preview to post RTW to make sure we don't miss anything. 

 This issue description will be continuously updated and will move between monthly sprints as we go.

After each doc is updated, update the What's new in ASP.NET Core 8.0 doc with links.  This has to be done fast since many folks are in that file, checked out no longer than 2 hours.

----------------------------
Links to Announcements/What's New:
- [What's new in ASP.NET Core 8.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0)
- [What's new in .NET 8  Preview](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8)

Devblogs.microsoft.com and other announcements:
- [ASP.NET Core updates in .NET Preview 1](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#http-3-enabled-by-default)
- [ASP.NET Core updates in .NET Preview 2](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-2/)
- [ASP.NET Core updates in .NET Preview 3](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-3/)
- [ASP.NET Core updates in .NET 8 Preview 4](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-4/)
- [ASP.NET Core updates in .NET 8 Preview 5](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/)
- [ASP.NET Core updates in .NET 8 Preview 6](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-6/)

----------------------------
**Tracking features to issues and PR's**

[Specify server timeout and keep alive interval settings using the HubConnectionBuilder](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#specify-server-timeout-and-keep-alive-interval-settings-using-the-hubconnectionbuilder) (Preview 1).   Look over the Blazor specific doc update here -wp: https://github.com/dotnet/AspNetCore.Docs/commit/f566ed91821e65ccd65142c3298d6d88cc403a3b
  - [x] Add new section in What's New: Complete.  See [What's New: New approach to set the server timeout and Keep-Alive interval](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0#new-approach-to-set-the-server-timeout-and-keep-alive-interval)
 
  - [x] Update SignalR config: [#29717](https://github.com/dotnet/AspNetCore.Docs/issues/29717)

[Seamless reconnect](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/#signalr) (Preview 5) plus the hub server opt-in config requirement `options.UseAcks` made available with preview 6.

  - [x] Add new section in What's New. #29741 
  
Note:  Future update but not this sprint for July 2023:
Once this feature has config finished, Update SignalR configuration topic to show how to enable and disable Seamless reconnect.  Given this feature is in early support phase in preview 5 and 6 and no configuration exists for it as of 7/17/23, I will wait to update this topic for this feature once configuration is in place in a later preview or the GA.

See somewhat related 8.0 feature tracking for gRPC: #28609

Old May [Associated WorkItem - 96055](https://dev.azure.com/msft-skilling/Content/_workitems/edit/96055)

---

**Comment by wadepickett** [comment]
Closing as tracked and updated for April.  Will re-open to track for March.

**Comment by wadepickett** [comment]
Re-opening to continue to track actively in May.

**Comment by wadepickett** [comment]
Verified: No new features or changes specifically for SignalR for preview 4 during May.   Closing this issue for tracking the review for features for SignalR in May.  Will recreate for June to review for next release.

[ASP.NET Core updates in .NET 8 Preview 4 - .NET Blog (microsoft.com)](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-4/)

**Comment by wadepickett** [comment]
Opening and tracking for June now.

**Comment by wadepickett** [comment]
Completed for July previews:  
Fixed with #29811, #29814, #29761
