### ISSUE TITLE
Blazor project tracking 2024

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#31423]
# 2024

## History

* [Blazor project tracking 2023 (dotnet/AspNetCore.Docs #28001)](https://github.com/dotnet/AspNetCore.Docs/issues/28001)
* [Blazor project tracking 2022 (dotnet/AspNetCore.Docs #24615)](https://github.com/dotnet/AspNetCore.Docs/issues/24615)
* [Blazor project tracking 2021 (dotnet/AspNetCore.Docs #19286)](https://github.com/dotnet/AspNetCore.Docs/issues/19286)

## .NET 10 Next Year

* [ ] .NET 10: File Upload work: https://github.com/dotnet/AspNetCore.Docs/pull/33357, https://github.com/dotnet/aspnetcore/issues/47301

## Doc ideas

Not **ALL** of these will be worked. This is an idea list/check list that don't rise to the level of opening an issue at this time.

* [ ] GDPR article for Blazor? https://github.com/dotnet/aspnetcore/issues/59457
* [ ] In the *Event Handling* article we just say that returning a task from an event handler *is supported.* Does the PU want to go further (i.e., a recommendation). Does the PU wish to say more about *fire-and-forget* `async void` versus `async Task`?
* [ ] I like this section https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-9.0&branch=pr-en-us-34298#totp-client-and-server-time-skew for both of the Blazor 2FA/TOTP articles.
* [ ] Updating `<script>` tag placement guidance on #34346; but in the context of https://github.com/dotnet/razor/pull/8744 and the original language, it isn't clear what "updated dynamically" means or "not do what they expect."
* [ ] Do we want to roll account confirmation with PW recovery and 2FA/TOTP into the WASM+Identity sample app, probably with them in a configurable state for enabling the features so that they don't break casual use of the sample without setting up an email provider. https://github.com/dotnet/AspNetCore.Docs/pull/34189#issuecomment-2536921077
* [ ] Do we want to add app roles, Azure Admin roles, and Azure security groups to our BWA+Entra article+sample? Can I just cross-link an existing BWA-Graph sample in either Graph or Identity docs? Either way, the *Application roles for apps registered with Microsoft Entra (ME-ID)* section of the BWA+OIDC article will have a cross-link or different guidance based on how this is handled.
* [ ] In the PU repo's project templates, the app settings JSON files don't have a LF on the last line of the file.
* [ ] See https://github.com/dotnet/aspnetcore/issues/58833 for coverage in the *Security and Identity* overview and note it in prerendering coverage at https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0#prerendering-guidance ... and note that https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0#prerendering-with-authentication is broken (at least for the 8.0 release).
* [ ] In the WASM+Identity sample app and article, adopt `EditForm` and DA in the `Login` and `Register` components.
* [ ] After https://github.com/dotnet/AspNetCore.Docs/pull/33934 and https://github.com/dotnet/AspNetCore.Docs/pull/33976 merge, add the key vault approach for the email provider API key to both of the acct conf+PW articles.
* [ ] For the BWA acct conf + PW recovery article, confirm that the wiring up of just the acct conf is enough to also activate the PW recovery part, which I don't recall if I tested or not at the time. It should just light up 💡 ... I think 🤔.
* [ ] `new()` and `new[] { }` for simplification `[]`. Some done on #33786 ... more to come.
* [ ] WasmBrowserApp: IntelliSense is saying to use local functions for the listener functions.
* [ ] For early 2025, get the [`FileUpload2` example (CSR)](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads#upload-files-to-a-server-with-client-side-rendering-csr) fully working for BWA and WASM samples. For BWA, the component is present, but there's no server controller to hit. For WASM, the component is in the WASM sample app but really should be moved to the new Call web API sample, where it can be made to work.
* [ ] Replace in-text (usually non-working) examples with `dotnet/blazor-samples`-based, fully working, cut-'n-paste examples. Might be best to create a list on an issue first, then I can work down the list.
* [ ] Apply form beautification 🌷 to the 8.0 sample app forms.
* [ ] Review *Dynamic and extensible authentication requests* for coverage opportunities https://github.com/dotnet/aspnetcore/issues/42580 https://github.com/dotnet/aspnetcore/pull/42692
* [ ] To show and explain anti-request forgery in the *File Uploads* topic, use some commented-out text held there to enable controller services with `AddControllersAndViews` ***and*** pass the anti-forgery token to the Blazor app (<8.0) or obtain it from the anti-forgery feature (>=8.0) for the POST.
* [ ] With `<NotFound>` going away for BWA at 8.0, I think a dedicated bit in the *Error handling* topic on processing 404s via built-in server middleware makes sense (i.e., `UseStatusCodePagesWithRedirects`). Be sure to search for it because a cross-link is required in at least one case where I left a NOTE about BWAs not using the Not Found content template any longer.
* [ ] Root-level cascading values followup items: https://github.com/dotnet/AspNetCore.Docs/pull/30095
* [ ] Custom ICU creation for WASM didn't make the cut for 8.0 or 9.0. It's scheduled for 10.0 now. https://github.com/dotnet/runtime/issues/82908
* [ ] I wasn't able to resolve #29448 with #29449 because I can't see how the implementation should be applied in the reader's example app to avoid the reported behavior. Will circle around to this subject with Javier after .NET 8 releases.
* [ ] [Revert content](https://github.com/dotnet/AspNetCore.Docs/pull/29130) ([Live content](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#azure-static-web-apps)) to a cross-link when [Azure Static Web Apps docs](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-blazor) get a tutorial/tooling guidance for the new publish from VS gesture. Tracking on Azure docs issue: https://github.com/MicrosoftDocs/azure-docs/issues/112013 **UPDATE (9/25/24)**: DR said he'd follow up with them because they closed the issue as a won't-fix.
* [ ] Need to keep an 👁️ on WebSockets with Azure Front Door remark in [this section](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/interactive-server-side-rendering?view=aspnetcore-8.0#client-connections). Not supported today, but they might have something 23H1 roll out per https://github.com/MicrosoftDocs/architecture-center/issues/1891#issuecomment-1284754716 and https://feedback.azure.com/d365community/idea/c8b1d257-8a26-ec11-b6e6-000d3a4f0789.
* [ ] Although I'm working the *Security* node passes in February, I'm going to handle one item separately after the passes are finished pertaining to handling refresh tokens from Razor components when a request fails (e.g., https://github.com/dotnet/AspNetCore.Docs/issues/26086). Javier said, "... it involves sending a request to the token endpoint of the OIDC/OAuth provider in the same way you do in a web application." The refresh token is available to components via `TokenProvider` in the current guidance, so it seems that the component calls a server API to hit up the IdP to renew (and get a new refresh token) with an update to the `TokenProvider` with the new tokens. The component continues processing transparently (re-initiates the web API call that it was making in the first place) after the server-side work. Cross-refs: https://github.com/dotnet/AspNetCore.Docs/issues/19797#issuecomment-779294104
    * Especially: https://github.com/dotnet/AspNetCore.Docs/issues/22405#issuecomment-849106466
    * ... and because it was never built-into the scaffolder to change the default logout page for Blazor Server: https://github.com/dotnet/Scaffolding/issues/1423 ... ***OR, alternatively*** ...
    * XSRF antiforgery token content exists and the component can pass it to the endpoint because I don't think we want to tell devs to decorate server-side endpoints with `@attribute [IgnoreAntiforgeryToken]`, including for logout. The coverage is at: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio#pass-an-xsrf-token-to-the-app
* [ ] Per Steve's .NET Conf talk, shouldn't we briefly cover [`FileSystem` API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem) use in Blazor apps?
* [ ] Let's run through the [`testassets` pieces in the framework](https://github.com/dotnet/aspnetcore/tree/main/src/Components/test/testassets) to see what might be helpful for devs to see in docs. It's a large task tho because there's so much there. This probably can't be worked in 23H1, possibly for 23Q3 tho.
* [ ] It would probably be nice to create a `QuickGrid` example that opens and closes a detail record component without losing the page and scroll position of the grid. For context, see https://github.com/dotnet/blazor-samples/issues/58.
* [ ] Do we want a cascading param state management example? https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-6.0&pivots=webassembly#additional-approaches-wasm https://github.com/dotnet/AspNetCore.Docs/issues/27296
* [ ] Best to have PU 🐈 look over the SignalR-Blazor enhancements for SignalR config (in the SignalR doc and the WASM/Server Host and Deploy docs) and SignalR client logging (in the Logging doc).
* [ ] Place element attributes in alphabetical order.

## Resolved

* [x] "MS Build" should have no space ... MSBuild. #32485
* [x] Check this https://github.com/dotnet/AspNetCore.Docs/pull/30792 to make sure the v5 code works. I think it will, but it's best to confirm it. I won't check it tho if Philip Reed gets back to me that it worked for him. **Resolved by #32108**.
* [x] There are some Razor code rendering problems that should be reported. *Done!* Via email DR is aware and said he'll try again to get it improved.
* [x] Preview notice in BWA+OIDC BFF pattern. **UPDATE**: Taken care of on an earlier PR.
* [x] Update INCLUDEs for introductions WRT the examples going into the sample apps. **INCLUDES removed, so no longer a concern.**
* [x] Find `XXX.Count() > 0` and swap for `.Any()`. #33475.
* [x] CODEOWNERS file updates for Blazor docs outside of the Blazor node. #33478
* [x] Blazor scaffolder location change in VS UI. #33481
* [x] Update the Blazor CRUD scaffolder to use IDbContextFactory instead of injecting the DbContext directly in to components ... https://github.com/dotnet/Scaffolding/issues/2693 ***Done!*** per the tutorial updates prior to merging the PR.
* [x] Promote NOTE on 'Avoid using a loop variable directly in a lambda expression' in *Images and Documents* article to article text. #33483
* [x] Merge https://github.com/dotnet/blazor-samples/pull/303 after open PRs are merged. ***Done!***
* [x] Bad phrase in the QR code doc: "placeholder is where the site (company) name" ... needs "goes" at the end. #33485
* [x] Use "session affinity" instead of "sticky sessions," but call out that "sticky sessions" is also a commonly-used term. #33487
* [x] Confirm Blazor docs use "Native AOT" ... not "native AOT." #33498
* [x] Confirm that "Razor Class Library" (proper noun) is only used for text that refers to the project template. All other instances should use adjective capitalization ("Razor class library"). This should already be the case, so hopefully few or no 😈 have gotten into the docs over the years. #33500 (only found in non-Blazor docs)
* [x] Convert table format over to the simplified structure without opening and closing pipes (`|`). #33560
* [x] Analyze where/how "by default" is used in Blazor docs. Eliminate it spots where it isn't necessary. Also, confirm affirmative reasons for because subordinate conjunctions. #33587
* [x] "Data Protection" should be capitalized when referring directly to the ASP.NET Core feature (service). #33607
* [x] RP/MVC tutorial movie attributions ... I don't think that they're present. **UPDATE**: Email sent to doc 🐈 🐈🐈.
* [x] Mirror stronger remarks in #32994 for https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity. #33610
* [x] Main doc set: The HTTPS Redirection Middleware says "always" redirects, but that's not exactly right ... it's if there's an HTTPS port available that it always redirects. #33613
* [x] I made the Blazor script placeholder lines **BOLD** on https://github.com/dotnet/AspNetCore.Docs/pull/31318 for the SignalR config doc. Do that ***everywhere*** across the Blazor docs. #33615
* [x] Naming: Check/change from 'Blazor WebAssembly runtime" or just "WebAssembly runtime" to ".NET WebAssembly" runtime. #33617
* [x] Make sure that `@using static Microsoft.AspNetCore.Components.Web.RenderMode` is in all of the 8.0+ `_Imports.razor` files. Per #31445. ***Confirmed OK!*** 👍 No action needed.
* [x] It's desirable to identify whether the request is GET or POST in `OnInitialized` or `OnParametersSetAsync` https://github.com/dotnet/aspnetcore/issues/51978 PR: #33630
* [x] For the RCL case in https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#load-a-script-from-an-external-javascript-file-js, it shouldn't break using `./`, but shouldn't we remove the `./` in the general case? #33632
* [x] Noting from a passing message because I don't think we cover it ... Does await `base.OnAfterRenderAsync(firstRender);` need to be called? No, we try to avoid making people call base on `ComponentBase` virtual methods. They can call it if they want but it’s a no-op. ***Covered!*** It was addressed on two PRs I believe within the last year or two.
* [x] Check on "anti-forgery" vs. "antiforgery" ... the style manual uses "antiforgery" (no hyphen), but Chicago calls for it IIRC. We mostly seem to use the hyphen with it. #33634
* [x] Confer with Artak on the correct PU group to add to the `dotnet/blazor-samples` repo. https://github.com/dotnet/blazor-samples/pull/136 ***Resolved!*** 👍 
* [x] Skipping API doc crosslinks for the *Routing* article because there's a large open PR on it. Circle back to it later. #33644
* [x] Check on "interactive `<Router>` (or routing or router)" language for cross-links to new guidance in the *Fundamentals* > *Routing* article. #33644
* [x] Check on places where the main (non-`.Client`) project is mentioned for BWAs and confirm that they're all described as the "server project." ***Checked!*** ... and seems ok.
* [x] Check back in 24Q1 on the doc Razor code formatting problem reported in https://github.com/dotnet/AspNetCore.Docs/issues/30157. ***Discussed*** with Dan offline.
* [x] Component param example for https://github.com/dotnet/aspnetcore/issues/49945#issuecomment-1671978729. #33648
* [x] `_`/`this` all the things ... https://github.com/dotnet/AspNetCore.Docs/issues/30533#issuecomment-1753219131. #33652
* [x] Consider moving the component example in [Handle caught exceptions outside of a Razor component's lifecycle](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#handle-caught-exceptions-outside-of-a-razor-components-lifecycle) into the sample apps. For an alternative approach, see https://github.com/dotnet/blazor-samples/pull/186. ***Nah!*** ... Let's go with what we have. WRT moving the sample to the sample app, let's leave it in place in the article for now.
* [x] Keeping an :eye: on https://github.com/dotnet/runtime/issues/98225 for an additional update to *Startup* article guidance in the *Configure the .NET WebAssembly runtime* section. #33658 ... Cross-link the issue that I opened for now. Will update text when they place docs.
* [x] Azure docs will host content+samples(s) for BWA+MS Identity Web+Azure hosting. Check back and cross-link to their new content when it appears. https://github.com/dotnet/AspNetCore.Docs/pull/31555#discussion_r1489472132 **UPDATE**: Seems that the project template is going to produce this. If we carry a sample app/article, it will be determined by and opened in relation to .NET 9 coverage at RC2. It's tracked by the .NET 9 tracking issue.
* [x] Consider https://github.com/dotnet/AspNetCore.Docs/pull/31118#issuecomment-1830820841 for coverage in 24H1. **UPDATE**: Per Mackinnon's remarks, let's NOT do anything about this at this time. He basically says that if they feel coverage is needed that they'll let me know.
* [x] For the [Standalone WASM w/Identity article+sample](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?view=aspnetcore-8.0): Swap `IdentityUser` for `AppUser` -AND- I need to cross-link in the article's remark for "advanced Identity features" to whatever the main doc set is going to have on the subject in the SPA/Identity docs. https://github.com/dotnet/AspNetCore.Docs/pull/31010#issuecomment-1810084642 **UPDATE**: The cross-link is already there, and we'll keep `AppUser` because the sample+article now manages user roles added to `IdentityUser`.
* [x] Custom auth state provider refactor to include WASM coverage. #33668
* [x] Blazor tutorial: Check and drop "trademark" for attributions. #33685
* [x] Include "NuGet package" in nuget.org cross-links to make it clear the link goes to the package and not the namespace/API doc. #33689 ... *BUT* had to close as a `won't-fix` scenario.
* [x] Bias-free communication sweep https://learn.microsoft.com/en-us/style-guide/bias-free-communication #33706
* [x] Better cross-link for SIMD references. #33708
* [x] Add nav menu cut-'n-paste snippets for our fully-working demos? **Won't fix** ... there are too many.
* [x] Investigate this Artak remark on MIA security remarks: https://github.com/dotnet/aspnetcore/issues/38486#issuecomment-973107723 #33723
* [x] When https://github.com/dotnet/docs/issues/27395 is resolved and Mono/WASM MSBuild props are covered, update the cross-links from the targets file to the new official doc. Links can be located on the PR that added them at https://github.com/dotnet/AspNetCore.Docs/pull/24493. **UPDATE (9/26/24)**: *It doesn't look like they're ever going to do this. I don't need to keep this item here because I'll be pinged per the open issue if they ever work it.*
* [x] Improve auth state provider docs per https://github.com/dotnet/aspnetcore/issues/47490. **UPDATE (9/26/24):** *Work was done on #33668, and there's a new dedicated custom auth state provider doc that has coverage for both server and client scenarios.*
* [x] There was no time to update the images for the [Lazy load assemblies article](https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-8.0). Consider bringing dev tools images back for the *Complete example* section. **Won't fix**: *The text calls out looking at the Network tab to see the assembly load. I don't think an image is needed.*
* [x] Check on antiforgery with the new standalone WASM w/Identity article scenario. **UPDATE (9/26/24)**: *There's a [section](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity?view=aspnetcore-8.0#antiforgery-support) covering this now, so we're good.*
* [x] Check again the new guidance on breaking on unhandled exceptions with ***normal*** VS in 24Q1. My Preview VS might be funky and not permitting it to work properly. Cross-ref: https://github.com/dotnet/AspNetCore.Docs/pull/30849 **UPDATE (9/26/24):** *AFAIK, the guidance is fine. We've worked on it and improved it since this tracking entry was placed here.*
* [x] Update for use of C# Dev Kit: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit ... .NET talk is at https://www.youtube.com/watch?v=tFCZw-wZVtg and there's a .NET Conf talk on it Day 1 - 3:45 **Resolved by #30443.*
* [x] Check `AuthorizeView` coverage for error/API described in https://github.com/dotnet/AspNetCore.Docs/issues/31119. **UPDATE (9/27)**: *Don't think we need to address this. BWA OOB (according to Jeremy) works with social logins, and the (client) App Id for the app registration is clearly delineated from the secret Id in the article. True that we don't have a sample app with social login(s), but we'll wait and see if issue(s) come in indicating problems.* 
* [x] C#12 primary ctors #33786
* [x] Update a handful of "Microsoft identity platform" instances with incorrect capitalization. #33808
* [x] Update title of BWA+Entra article to include "ID." #33872
* [x] Per the discussion at #29749, consider a more general demo of a state management service that works across clients/circuits. **UPDATE**: We'll let this stand for now on the updates that were made.
* [x] Check the [debugging guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio#debug-in-the-browser) to confirm that it didn't regress at .NET 8 and confirm the presence of the `file://` pages for debugging on the client. #33887
* [x] Convert the Blazor-EFCore sample app's manual grid to use a GridView? **UPDATE**: Actually, the way to address this is just to cross-link the new movie tutorial, which uses QuickGrid. #33889
* [x] See about placing the Key Vault code in the BWA+OIDC and BWA+MS Identity Web articles. #33934
* [x] Update a couple of spots where `@inject NavigationManager NavigationManager` crept into code examples.
* [x] See if I can drop the sample code and versioning from the [ToDo List tutorial](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-8.0) and just go with NRT code throughout. Add an NRT note to the top for <6.0 (C# 10). ***Naaaah!*** Decided not to do this ... at least for the time being.
* [x] Confirm update the sample app lists in the sample repo README and the *Fundamentals* > *Overview* article. Add/improve article linking from the samples repo. #33987 https://github.com/dotnet/blazor-samples/pull/386

## PU review items

Steve:

* [ ] API of last paragraph in https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?view=aspnetcore-8.0.

Halter:

* [ ] Halter to review [this section](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio#authentication-state-management-at-sign-out).
* [ ] Confirm scope and authority guidance in the BWA+OIDC article that was added on 3/26 on #32149.
* [ ] The following went in without review because they sat for weeks without response and without answers to email requests for review:
  * https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-entra?view=aspnetcore-9.0#azure-key-vault
  * https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-identity/account-confirmation-and-password-recovery?view=aspnetcore-9.0

Javier:

* [ ] Ask Javier about https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/MarkupBlockComponent.razor#L37C21-L37C37 because we say in the *Threat Mitigation* topic not to use `builder.AddMarkupContent(0, someUserSuppliedString)` because it can create an XSS vulnerability.

Mackinnon:

* [ ] The section https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-9.0#websocket-compression-for-interactive-server-components wasn't reviewed ... no one was available to look. 
* [ ] "SSR" interpretation in the framework code+comments isn't "static server rendering." Discuss further, including earlier remarks that the terminology choices weren't what was expected. https://github.com/dotnet/AspNetCore.Docs/issues/33843
* [ ] [Confirm language](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#interactive-server-side-rendering-interactive-ssr) on interactive SSR components in the `Pages` folder of the `.Client` project. Removed on https://github.com/dotnet/AspNetCore.Docs/pull/34050 per DR's request. A PU issue where Javier says that it's correct: https://github.com/dotnet/aspnetcore/issues/58944#issuecomment-2479063422
* [ ] Put an :eye: on one line in particular in the [prerendering with JS interop](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#prerendering-with-javascript-interop) INCLUDE file: *An infinite loop isn't created because `StateHasChanged` is only called when `scrollPosition` is `null`.*
* [ ] Review of the new section on custom input components at https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?view=aspnetcore-8.0#custom-input-components.
* [ ] Review of https://learn.microsoft.com/en-us/aspnet/core/blazor/images-and-documents
* [ ] Confirm `addHandlers` module FN approach for wiring up event handlers.
* [ ] When he's free, check on the param expression bit added by #32511.
* [ ] The framework does what we say devs aren't supposed to do on transient disposables for `IHttpClientFactory`/`HttpClient`.
* [ ] Why I couldn't load a script via control of `<head>` content for the JS collocation example. `<HeadContent><script src="./Components/Pages/JsCollocation1.razor.js"></script></HeadContent>`
* [ ] Check on the namespace section in the Components overview.
* [ ] Check on the "In components derived from the base class" bit in the DI topic. It doesn't make sense. It might be incorrect.
* [ ] Review of the new example at [*Fundamentals* > *DI* > *Utility base component classes to manage a DI scope* section](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/dependency-injection#utility-base-component-classes-to-manage-a-di-scope).
* [ ] The **_WHY_** aspects on https://github.com/dotnet/AspNetCore.Docs/pull/26620#issuecomment-1205513721. I'd like to know why the RID works with the MSBuild prop (`/p:RuntimeIdentifier={RID}` but the self-contained setting doesn't (`/p:SelfContained=false`).
* [ ] Review the code for streaming `<textarea>` content in a form of #29541. [Live](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components#large-form-payloads-and-the-signalr-message-size-limit)
* [ ] Ask about https://docs.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?view=aspnetcore-6.0 per https://github.com/dotnet/AspNetCore.Docs/pull/26557. Is this the best way to showcase event callbacks with dynamic components?
* [ ] In `UserClaims` components (and perhaps a few other spots) the code for a collection displayed in the UI can can have the collection be assigned an empty value or left nullable with an additional Razor nullable check. Which is best? There's a text file on the desktop with the code either way.
* [ ] Do we need to assess all Blazor examples where tasks are awaited looking for spots where it would be more appropriate to avoid resuming with the context (`ConfigureAwait(false)`)?
* [ ] Ask about the Task method without async and await keywords ... https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppEFCore/Components/ContactForm.razor#L111-L116
* [ ] IntelliSense is saying that these should be auto properties ... https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppEFCore/Components/ContactRow.razor#L50-L61 ***AND*** https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppEFCore/Components/Pages/Home.razor#L98-L106

## UE pass tracking

- [ ] Debug WebAssembly &mdash; Resolve :point_right: #23373 ... and we'll probably need to show full files everywhere we refer to `tasks.json`/`launch.json` due to https://github.com/OmniSharp/omnisharp-vscode/issues/4542. See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/23777
- [ ] WebAssembly native dependencies
- [ ] Test components - Specifically, let's consider hosting example component tests for WASM and Server (`TestServer`). https://github.com/dotnet/AspNetCore.Docs/issues/25263
- [ ] Host and deploy: Apache for hosted WASM/sub-app scenarios might need more work. See 👉 https://github.com/dotnet/AspNetCore.Docs/pull/24519#issuecomment-1008480134.
  - [ ] Overview &mdash; Perhaps for *Routing*, too, but clarify the navigation behavior of `NavigationManager.NavigateTo`. See :point-right: https://github.com/dotnet/AspNetCore.Docs/pull/22146#issuecomment-827802596.
  - [ ] Blazor Server &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21226
  - [ ] Blazor WebAssembly &mdash; See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/19979 and https://github.com/dotnet/AspNetCore.Docs/issues/21829#issuecomment-803192673 and validate `web.config` post PR https://github.com/dotnet/AspNetCore.Docs/pull/24950 and in light of discussion on https://stackoverflow.com/a/69888016 and https://stackoverflow.com/a/70967738. Probably add a tagged SO filter link: `https://stackoverflow.com/questions/tagged/blazor+iis+compression`
  - [ ] WebAssembly deployment layout
- [ ] Blazor Server and EF Core &mdash; Consider using the QuickGrid now that it's a supported part of the framework.

## UE pass tracking

Articles that could benefit from the 🦖 **Rex Treatment**&trade; 🦖 ...

* Security node for 8.0/BWA/Identity components
* Blazor Server and EF Core
* Call web API topic: I'd like to divorce this from the main doc set's web API article in favor of a small Minimal APIs-based web API app for the experiences in the topic. I think churn on the main doc set article may have broken the cut-'n-paste, fully working examples that I have. I either need to update the examples to match the latest guidance in the web API article or place a dedicated app example in this topic, and I favor the latter because of on-going web API article churn ... this is a fragile 💥 setup because I don't maintain both articles.
* File Uploads article
* File Downloads article
* Test article
* PWA article
* Performance best practices article
* State Management article
* Virtualization article: https://github.com/dotnet/AspNetCore.Docs/issues/27537
* Blazor Hybrid
  * Overview
  * Tutorials
    * Overview
    * .NET MAUI
    * Windows Forms
    * WPF
  * Routing and navigation
  * Static files
  * Dev Tools
  * Reuse components

New for 8.0 ...

* ASP.NET Core Razor class libraries (RCLs) with static server-side rendering (static SSR)
* Integrate ASP.NET Core Razor components into ASP.NET Core apps
* Prerender ASP.NET Core Razor components
* Render Razor components outside of ASP.NET Core
* ASP.NET Core Blazor render modes
* ASP.NET Core Blazor sections
* Troubleshoot ASP.NET Core Blazor Hybrid
* ASP.NET Core Blazor JavaScript with static server-side rendering (static SSR)
* Threat mitigation guidance for ASP.NET Core Blazor static server-side rendering
* Secure ASP.NET Core Blazor WebAssembly with ASP.NET Core Identity
