### ISSUE TITLE
Update ASP.NET Core fundamentals docs to highlight Blazor

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#34356]
[EDIT by guardrex to add a remark at the top.]

### Description

See https://github.com/dotnet/AspNetCore.Docs/issues/33127#issuecomment-2243302843:

> Actually, looking through all of the ASP.NET Core fundamentals topics, it looks like we should do a general pass through those topics to shift them from Razor Pages to Blazor.

- [ ] 🚧 ***In-progress!*** 👷‍♂️ Overview (fundamentals/index) - Tracked by [37558](https://github.com/dotnet/AspNetCore.Docs/issues/37558).
- [ ] App start up (fundamentals/startup) - #34358
- [ ] Dependency injection (services) (fundamentals/dependency-injection) - #34417
- [ ] Native AOT
     - [ ] Overview (fundamentals/native-aot)
     - [ ] Tutorial (fundamentals/native-aot-tutorial)
     - [ ] Request Delegate Generator (fundamentals/aot/rdg)
- [ ] Middleware
     - [ ] Middleware overview (fundamentals/middleware/index) - #34383
     - [ ] Write middleware (fundamentals/middleware/write)
     - [ ] Request and response operations (fundamentals/middleware/request-response)
     - [ ] Request decompression (fundamentals/middleware/request-decompression)
     - [ ] Factory-based middleware (fundamentals/middleware/extensibility)
     - [ ] Factory-based middleware with third-party container (fundamentals/middleware/extensibility-third-party-container)
- [ ] Host
     - [ ] WebApplication and WebApplicationBuilder (fundamentals/minimal-apis/webapplication)
     - [ ] Generic Host (fundamentals/host/generic-host)
     - [ ] Web Host (fundamentals/host/web-host)
- [ ] Configuration (fundamentals/configuration/index)
- [ ] Options (fundamentals/configuration/options)
- [ ] Environments (dev, stage, prod) (fundamentals/environments)
- [ ] Logging and monitoring
     - [ ] Logging (fundamentals/logging/index)
     - [ ] HTTP logging (fundamentals/http-logging/index)
     - [ ] Enrich HTTP request logs in ASP.NET Core (fundamentals/http-logging/http-log-enricher)
     - [ ] W3C logger (fundamentals/w3c-logger/index)
- [ ] HttpContext (fundamentals/use-httpcontext) - #34367
- [ ] Routing (fundamentals/routing)
- [ ] Handle errors (fundamentals/error-handling)
- [ ] Make HTTP requests (fundamentals/http-requests)
- [ ] Static files (fundamentals/static-files)
- [ ] Validation (fundamentals/validation)
- [ ] dotnet-scaffold telemetry (fundamentals/dotnet-scaffold-telemetry)

Note: *Metrics* coverage was moved on #37547.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/index.md

### Document ID

8e663029-63b9-2622-f852-9f8a2ec70db3

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+8e663029-63b9-2622-f852-9f8a2ec70db3)

---
[Associated WorkItem - 354367](https://dev.azure.com/msft-skilling/Content/_workitems/edit/354367)

**Comment by guardrex** [comment]
As I work through highlighting Blazor in main doc set articles, I can see that this article list isn't complete or updated. I've made a note to update it, ~and I hope to take care of it within a week or two.~ I intended to return to the list but haven't been able to under the workload. ~I'll see if I can reach it soon!~ 🏃‍♂️ 

**UPDATE**: Still working through the authz node. I'll get back to this when I'm done with that node.

**Comment by guardrex** [comment]
@tdykstra ... If it's Ok with you, let me take this one. Beyond the annual releases, product unit doc support, and community issue management/resolution, I think I can do the most good here. I just had a [successful run with the authz node](https://github.com/dotnet/AspNetCore.Docs/issues/35801), and I think with @danroth27's blessing that I probably should keep going. My goal isn't merely to focus on Blazor/Minimal API updates but also to give the articles the full 🦖 *Rex Treatment*&trade; 😄, delivering complete overhauls and resolving years-old issues that have been lying around on the repo forever. Of course, re-assign yourself back to this issue if you want to work it. @danroth27 will also let us know if he'd rather me focus on something else.

I'll be surveying the doc set to confirm/update this list of articles and getting started on them soon because we have a delay to mid-September waiting on the scaffolder updates to go public. I need those updates to finish the authz node Blazor updates. The last article to address in that node is the tutorial, which relies on scaffolded bits.
